version: '1.5'

services:
  api:
    container_name: API_requests_to_Midjourney
    build: .
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - .:/app
    ports:
      - 8000:8000
    environment:
      CLIENT_TOKEN: ${CLIENT_TOKEN}
      GUILD_ID: ${GUILD_ID}
      CHANNEL_ID: ${CHANNEL_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
      - worker
    env_file:
      - .env
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8000
  worker:
    build: .
    command: celery -A api.tasks.celery worker --concurrency=3 --loglevel=info
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - .:/app
    environment:
      GUILD_ID: ${GUILD_ID}
      CLIENT_TOKEN: ${CLIENT_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379

 
    